pipeline {
  agent {
    docker {
      // Large image with full OpenModelica build dependencies; lacks omc and OMPython
      label 'linux'
      image 'julia:1.2-buster'
      alwaysPull  true
      args '--privileged'
    }
  }
  options {
    skipDefaultCheckout true
  }
  stages {
    stage('build') {
      environment {
        USER = 'jenkins'
      }
      steps {
        dir("MetaModelica.jl") {
          checkout scm
          sh '''
          export HOME=$PWD
          julia -e "using Pkg;
          Pkg.add(\\"ExportAll\\");
          Pkg.add(\\"DataStructures\\");
          Pkg.add(\\"MacroTools\\");
          Pkg.add(\\"Test\\");
          Pkg.add(PackageSpec(url=\\"https://github.com/OpenModelica/ImmutableList.jl\\");
          Pkg.develop(PackageSpec(path=\\".\\"));
          Pkg.test())"
          '''
        }
      }
    }
  }
}
