pipeline {
  agent {
    docker {
      // Large image with full OpenModelica build dependencies; lacks omc and OMPython
      label 'linux'
      image 'julia:1.12.0-bookworm'
      alwaysPull  true
      args '--privileged'
    }
  }
  options {
    skipDefaultCheckout true
  }
  stages {
    stage('build') {
      environment {
        USER = 'jenkins'
      }
      steps {
        dir("MetaModelica.jl") {
          checkout scm
          sh '(pwd)'
          // ImmutableList 0.3.x ships from OpenModelicaRegistry, not General.
          sh '''
          export HOME=$PWD
          julia -e "using Pkg
                    Pkg.Registry.add(\\"General\\")
                    Pkg.Registry.add(RegistrySpec(url=\\"https://github.com/OpenModelica/OpenModelicaRegistry\\"))"
          '''
          sh 'export HOME=$PWD; julia -e "using Pkg; Pkg.add(PackageSpec(path=\\".\\"))"'
          sh 'export HOME=$PWD; julia -e "using Pkg; Pkg.test(\\"MetaModelica\\", coverage=true)"'
        }
      }
    }
  }
}
