pipeline {
  agent {
    docker {
      // Large image with full OpenModelica build dependencies; lacks omc and OMPython
      label 'linux'
      image 'julia:1.3.1-buster'
      alwaysPull  true
      args '--privileged'
    }
  }
  options {
    skipDefaultCheckout true
  }
  stages {
    stage('build') {
      environment {
        HOME = '/home/julia'
        USER = 'jenkins'
      }
      steps {
        dir("MetaModelica.jl") {
          checkout scm
          sh 'julia -e "using Pkg; Pkg.add(\\"ExportAll\\"); Pkg.add(\\"DataStructures\\"); Pkg.add(\\"MacroTools\\"); Pkg.add(\\"https://github.com/OpenModelica/ImmutableList.jl\\"); Pkg.test(\\"MetaModelica\\", coverage=true)"'
        }
      }
    }
  }
}
