#=
  This file contains all functions that should be exported for the MetaModelica runtime.
  Add new exports here :)
=#
export boolAnd
export boolOr
export boolEq
export boolString
export intAdd
export intSub
export intMul
export intMul
export intDiv
export intMod
export intMax
export intMin
export intAbs
export intNeg
export intLt
export intLe
export intEq
export intNe
export intGe
export intGt
export intBitNot
export intBitOr
export intBitXor
export intBitLShift
export intBitRShift
export intReal
export intString
export realAdd
export realSub
export realMul
export realDiv
export realMod
export realPow
export realMax
export realMin
export realAbs
export realNeg
export realNeg
export realLt
export realLe
export realEq
export realNe
export realGe
export realGt
export realInt
export realString
export stringCharInt
export intStringChar
export stringInt
export stringReal
export stringListStringChar
export stringAppendList
export stringDelimList
export stringLength
export stringEmpty
export stringGet
export stringGetStringChar
export stringUpdateStringChar
export stringAppend
export stringEqual
export stringCompare
export stringHash
export stringHashDjb2
export stringHashSdbm
export substring
export listAppend
export listReverse
export listReverseInPlace
export listLength
export listMember
export listGet
export listRest
export listHead
export listDelete
export listEmpty
export cons
export arrayLength
export arrayEmpty
export arrayGet
export arrayCreate
export arrayList
export listArray
export arrayUpdate
export arrayCopy
export arrayAppend
export anyString
export printAny
export debug_print
export tick
export equality
export setGlobalRoot
export valueConstructor
export valueSlots
export valueEq
export valueCompare
export valueHashMod
export referenceEq
export referencePointerString
export clock
export isNone
export isSome
export listStringCharString
export stringCharListString
export fail
export setStackOverflowSignal
export referenceDebugString
export isPresent
