#=
  This file contains all functions that should be exported for the MetaModelica runtime.
  Add new exports here :)
=#
export anyString
export arrayAppend
export arrayCopy
export arrayCreate
export arrayEmpty
export arrayGet
export arrayLength
export arrayList
export arrayUpdate
export boolAnd
export boolEq
export boolOr
export boolString
export clock
export cons
export debug_print
export equality
export fail
export getGlobalRoot
export intAbs
export intAdd
export intBitLShift
export intBitNot
export intBitOr
export intBitRShift
export intBitXor
export intDiv
export intEq
export intGe
export intGt
export intLe
export intLt
export intMax
export intMin
export intMod
export intMul
export intMul
export intNe
export intNeg
export intReal
export intString
export intStringChar
export intSub
export isNone
export isPresent
export isSome
export listAppend
export listArray
export listDelete
export listEmpty
export listGet
export listHead
export listLength
export listMember
export listRest
export listReverse
export listReverseInPlace
export listStringCharString
export printAny
export realAbs
export realAdd
export realDiv
export realEq
export realGe
export realGt
export realInt
export realLe
export realLt
export realMax
export realMin
export realMod
export realMul
export realNe
export realNeg
export realNeg
export realPow
export realString
export realSub
export referenceDebugString
export referenceEq
export referencePointerString
export setGlobalRoot
export setStackOverflowSignal
export stringAppend
export stringAppendList
export stringCharInt
export stringCharListString
export stringCompare
export stringDelimitList
export stringEmpty
export stringEqual
export stringEq
export stringGet
export stringGetStringChar
export stringHash
export stringHashDjb2
export stringHashSdbm
export stringInt
export stringLength
export stringListStringChar
export stringReal
export stringUpdateStringChar
export substring
export tick
export valueCompare
export valueConstructor
export valueEq
export valueHashMod
export valueSlots
export _listAppend
export getInstanceName
