#=
The MetaModelica runtime. This file is partly generated by the transpiler.
Functions marked "Defined in the runtime" are defined in the compiler C runtime
and interface with Boehm GC. They should be reimplemented here or removed.
=#

struct MetaModelicaGeneralException <: MetaModelicaException
  msg::Any
end

"""
SOME
Optional with a value T
"""
struct SOME{T}
  data::T
end

"""The optional type is defined as the Union of SOME{T} and the Nothing type. """
const Option{T} = Union{SOME{T},Nothing}

""" NONE is defined as nothing. """
const NONE() = Nothing()

Base.convert(::Type{Option{S}}, x::SOME{T}) where {S,T<:S} =
  let
    SOME{S}(convert(S, x.data))
  end

Base.convert(::Type{Option{T}}, nothing) where {T} =
  let
    Nothing()
  end

""" Identity case """
Base.convert(::Type{Union{Nothing,SOME{T}}}, x::Union{Nothing,SOME{T}}) where {T} =
  let
    x
  end

Base.convert(::Type{Union{Nothing,SOME{S}}}, x::SOME{S}) where {S} =
  let
    x
  end

""" Logically combine two Booleans with 'and' operator """
@inline function boolAnd(b1::Bool, b2::Bool)::Bool
  b1 && b2
end

""" Logically combine two Booleans with 'or' operator """
@inline function boolOr(b1::Bool, b2::Bool)::Bool
  b1 || b2
end

""" Logically invert Boolean value using 'not' operator """
@inline function boolNot(b::Bool)::Bool
  !b
end

""" Compares two Booleans """
@inline function boolEq(b1::Bool, b2::Bool)::Bool
  b1 === b2
end

""" Returns \\\"true\\\" or \\\"false\\\" string """
@inline function boolString(b::Bool)::String
  b ? "true" : "false"
end

""" Adds two Integer values """
@inline function intAdd(i1::T, i2::T) where {T <: Integer}
  i1 + i2
end

""" Subtracts two Integer values """
@inline function intSub(i1::T, i2::T) where {T <: Integer}
  i1 - i2
end

""" Multiplies two Integer values """
@inline function intMul(i1::T, i2::T) where {T <: Integer}
  i1 * i2
end

""" Divides two Integer values """
@inline function intDiv(i1::T, i2::T) where {T <: Integer}
  div(i1, i2)
end

""" Calculates remainder of Integer division i1/i2 """
@inline function intMod(i1::T, i2::T) where {T <: Integer}
  mod(i1, i2)
end

""" Returns the bigger one of two Integer values """
@inline function intMax(i1::T, i2::T) where {T <: Integer}
  max(i1, i2)
end

""" Returns the smaller one of two Integer values """
@inline function intMin(i1::T, i2::T) where {T <: Integer}
  min(i1, i2)
end

""" Returns the absolute value of Integer i """
@inline function intAbs(i::Int)
  abs(i)
end

""" Returns negative value of Integer i """
@inline function intNeg(i::Int)
  -i
end

""" Returns whether Integer i1 is smaller than Integer i2 """
@inline function intLt(i1::T, i2::T)::Bool where {T <: Integer}
  i1 < i2
end

""" Returns whether Integer i1 is smaller than or equal to Integer i2 """
@inline function intLe(i1::T, i2::T)::Bool where {T <: Integer}
  i1 <= i2
end

""" Returns whether Integer i1 is equal to Integer i2 """
@inline function intEq(i1::T, i2::T)::Bool where {T <: Integer}
  i1 == i2
end

""" Returns whether Integer i1 is not equal to Integer i2 """
@inline function intNe(i1::T, i2::T)::Bool where {T <: Integer}
  i1 != i2
end

""" Returns whether Integer i1 is greater than or equal to Integer i2 """
@inline function intGe(i1::T, i2::T)::Bool where {T <: Integer}
  i1 >= i2
end

""" Returns whether Integer i1 is greater than Integer i2 """
@inline function intGt(i1::T, i2::T)::Bool where {T <: Integer}
  i1 > i2
end

""" Returns bitwise inverted Integer number of i """
@inline function intBitNot(i::T) where {T <: Integer}
  ~i
end

""" Returns bitwise \'and\' of Integers i1 and i2 """
@inline function intBitAnd(i1::T, i2::T) where {T <: Integer}
  i1 & i2
end

""" Returns bitwise 'or' of Integers i1 and i2 """
@inline function intBitOr(i1::T, i2::T) where {T <: Integer}
  i1 | i2
end

""" Returns bitwise 'xor' of Integers i1 and i2 """
@inline function intBitXor(i1::T, i2::T) where {T <: Integer}
  i1 ⊻ i2
end

""" Returns bitwise left shift of Integer i by s bits """
@inline function intBitLShift(i::Int, s::Int)
  i << s
end

""" Returns bitwise right shift of Integer i by s bits """
@inline function intBitRShift(i::Int, s::Int)
  i >> s
end

""" Converts Integer to Real """
@inline function intReal(i::Int)::Float64
  Float64(i)
end

""" Converts Integer to String """
@inline function intString(i::Int)::String
  string(i)
end

@inline function realAdd(r1::Float64, r2::Float64)::Float64
  r1 + r2
end

@inline function realSub(r1::Float64, r2::Float64)::Float64
  r1 - r2
end

@inline function realMul(r1::Float64, r2::Float64)::Float64
  r1 * r2
end

@inline function realDiv(r1::Float64, r2::Float64)::Float64
  r1 / r2
end

@inline function realMod(r1::Float64, r2::Float64)::Float64
  mod(r1, r2)
end

@inline function realPow(r1::Float64, r2::Float64)::Float64
  r1^r2
end

@inline function realMax(r1::Float64, r2::Float64)::Float64
  max(r1, r2)
end

@inline function realMin(r1::Float64, r2::Float64)::Float64
  min(r1, r2)
end

@inline function realAbs(x::Float64)::Float64
  abs(x)
end

@inline function realNeg(x::Float64)::Float64
  -x
end

@inline function realLt(x1::Float64, x2::Float64)::Bool
  x1 < x2
end

@inline function realLe(x1::Float64, x2::Float64)::Bool
  x1 <= x2
end

@inline function realEq(x1::Float64, x2::Float64)::Bool
  x1 == x2
end

@inline function realNe(x1::Float64, x2::Float64)::Bool
  x1 != x2
end

@inline function realGe(x1::Float64, x2::Float64)::Bool
  x1 >= x2
end

@inline function realGt(x1::Float64, x2::Float64)::Bool
  x1 > x2
end

@inline function realInt(r::Float64)
  Integer(trunc(r))
end

@inline function realString(r::Float64)::String
  string(r)
end

function stringCharInt(ch::String)
  local i::Int = Int64(ch[1])
  i
end

function intStringChar(i::Int)::String
  local ch::String = string(Char(i))
  ch
end

function stringInt(str::String)
  local i::Int = Int64(str)
  i
end

""" This function fails unless the whole string can be consumed by strtod without
setting errno. For more details, see man 3 strtod """
function stringReal(str::String)::Float64
  local r::Float64 = parse(Float64, str)
  r
end

""" O(str) """
function stringListStringChar(str::String)::List{String}
  local chars::List{String} = nil
  for i = length(str):-1:1
    chars = _cons(string(str[i]), chars)
  end
  chars
end

""" O(str) """
function stringAppendList(strs::List{String})::String
  buf = IOBuffer()
  for n in strs
    print(buf, n)
  end
  String(take!(buf))
end

""" O(str)
  Takes a list of strings and a string delimiter and appends all
  list elements with the string delimiter inserted between elements.
  Example: stringDelimitList({\"x\",\"y\",\"z\"}, \", \") => \"x, y, z\"
"""
function stringDelimitList(strs::List{String}, delimiter::String)::String
  buffer = IOBuffer()
  local strsTmp::List{String} = strs
  local i::Int = 1
  while strsTmp !== nil
    @match Cons{String}(n, strsTmp) = strsTmp
    if i == 1
      print(buffer, n)
    else
      print(buffer, delimiter)
      print(buffer, n)
    end
    i += 1
  end
  return String(take!(buffer))
end


function stringDelimitList(strs::Vector, delimiter::String)::String
  buffer = IOBuffer()
  for (i,n) in enumerate(strs)
    if i == 1
      print(buffer, n)
    else
      print(buffer, delimiter)
      print(buffer, n)
    end
  end
  return String(take!(buffer))
end

stringDelimitList(lst::Nil, delim::String) = ""

""" O(1) """
@inline function stringLength(str::String)
  length(str)
end

""" O(1) """
@inline function stringEmpty(str::String)::Bool
  length(str) == 0
end

""" O(1) """
@inline function stringGet(str::String, index::Int)
  str[index]
end

""" O(1) """
function stringGetStringChar(str::String, index::Int)::String
  if index < 0
    println("stringGetStringChar: index < 0!")
    fail()
  end
  local ch::String = string(str[index])
  ch
end

""" O(n) """
function stringUpdateStringChar(str::String, newch::String, index::Int)::String
  local news::String = str
  if index < 0
    println("stringUpdateStringChar: index < 0!")
    fail()
  end
  news[index] = newch[1]
  news
end

""" O(s1+s2) """
@inline function stringAppend(s1::String, s2::String)::String
  s1 * s2
end

""" O(N) """
@inline function stringEq(s1::String, s2::String)::Bool
  s1 == s2
end

""" O(N) """
@inline function stringEqual(s1::String, s2::String)::Bool
  s1 == s2
end

@inline function stringCompare(s1::String, s2::String)
  cmp(s1, s2)
end

@inline function myhash(s::String)
  mod(hash(s), typemax(Int))
end

@inline function stringHash(str::String)
  Int(myhash(str))
end

""" Standard djb2 hash over UTF-8 code units. """
@inline function stringHashDjb2(str::String)
  h = UInt(5381)
  for byte in codeunits(str)
    h = ((h << 5) + h) + UInt(byte)
  end
  Int(h % UInt(typemax(Int)))
end

""" Does hashing+modulo without intermediate results. """
@inline function stringHashDjb2Mod(str::String, m::Int)
  h = UInt(5381) % UInt(m)
  for byte in codeunits(str)
    h = (((h << 5) + h) + UInt(byte)) % UInt(m)
  end
  Int(h)
end

@inline function stringHashSdbm(str::String)
  Int(myhash(str))
end

function substring(str::String, start::Int, stop::Int)::String #= stop index, first character is 1 =#
  if start < 0
    println("substring: start < 0!")
    fail()
  end
  local out = str[start:stop]
  out
end

""" O(1) ? """
@inline function arrayLength(arr::Array{T}) where {T}
  length(arr)
end

""" O(1) """
@inline function arrayEmpty(arr::Array{A})::Bool where {A}
  length(arr) == 0
end

""" O(1) """
function arrayGet(arr::Array{A}, index::Int) where {A}
  if index < 0
    println("arrayGet: index < 0!")
    fail()
  end
  arr[index]
end

""" O(size) """
@inline function arrayCreate(size::Int, initialValue::A) where {A}
  fill(initialValue, size)
end

""" O(N) """
function arrayList(arr::Array{T}) where {T}
  local lst::List{T} = nil
  for i = length(arr):-1:1
    lst = Cons{T}(arr[i], lst)
  end
  lst
end

""" O(n) """
function listArray(lst::Cons{T}) where {T}
  local N = length(lst)
  local arr::Vector{T} = Vector{T}(undef, N)
  i = 1
  while lst !== nil
    arr[i] = lst.head
    i += 1
    lst = lst.tail
  end
  return arr
end

""" O(1) """
function listArray(lst::Nil)
  []
end

"""
O(n)

Same as listArray but with a dummy argument to specify the type.
"""
function listArray(lst::Cons{T}, ty) where {T}
  local N = length(lst)
  local arr = Vector{ty}(undef, N)
  i = 1
  while lst !== nil
    arr[i] = lst.head
    i += 1
    lst = lst.tail
  end
  return arr
end

"""
Same as listArray but with a dummy argument to specify the type.
"""
function listArray(lst::Nil, ty)
  ty[]
end

""" O(1) """
function arrayUpdate(arr::Array{A}, index::Int,
                     newValue::B)::Array{A} where {A,B}
  arr[index] = newValue
  arr #= Same as the input array; used for folding. =#
end

""" O(n) """
@inline function arrayCopy(arr::Array{A})::Array{A} where {A}
  copy(arr)
end

""" Appends arr2 to arr1. O(length(arr1) + length(arr2)).
Note that this operation is *not* destructive, i.e. a new array is created. """
function arrayAppend(arr1::Array{A}, arr2::Array{A})::Array{A} where {A}
  local arr::Array{A}
  @error "Defined in the runtime"
  fail()
end

"""
Returns the string representation of any value.
Rather slow; only use this for debugging!
"""
function anyString(a::A) where {A}
  string(dump(a))
end

""" print(anyString(a)), but to stderr """
function printAny(a::A) where {A}
  println(dump(a))
end

""" For RML compatibility """
function debug_print(str::String, a::A) where {A}
  println(str)
  @show a
end

let tickCounter = 0
  global function tick()
    tickCounter += 1
  end
  global function resetTick()
    tickCounter = 0
  end
end

function equality(a1::A1, a2::A2) where {A1,A2}
  if !valueEq(a1, a2)
    fail()
  end
end

#=
globalRoots cannot use `nothing` for unset entries because NONE() is `nothing`.
Use `missing` to signal that an element is not set.
=#

""" Sets the index of the root variable with index 1..1024
This is a global mutable value and should be used sparingly.
You are recommended not to use "missing" the runtime system treats this values as uninitialized and fail getGlobalRoot later on.
"""
const global globalRoots::Vector{Any} = Vector{Any}(missing, 1024)

function setGlobalRoot(index::Int, value::T) where {T}
  if index > 1023 || index < 0
    fail()
  end
  globalRoots[index+1] = value
end

function getGlobalRoot(index::Int)
  if index > 1023 || index < 0
    fail()
  end
  val = globalRoots[index+1]
  if ismissing(val)
    fail()
  end
  val
end

""" The return-value is compiler-dependent on the runtime implementation of
boxed values. The number of bits reserved for the constructor is generally
between 6 and 8 bits. """
function valueConstructor(value)
  #= Approximation of the runtime boxed-value constructor tag. =#
  local h::Int = mod(hash(typeof(value)), typemax(Int))
  local ctor::Int = h
  ctor
end

""" The number of slots a boxed value has. This is dependent on sizeof(void*)
on the architecture in question. """
function valueSlots(value::A) where {A}
  local slots::Int = 0
  try
    slots = nfields(value)
  catch ex
    #= Leave slots at 0 for values without fields. =#
  end
  slots
end

""" Structural equality """
function valueEq(a1::A, a2::B)::Bool where {A,B}
  local b::Bool = @match (a1, a2) begin
    (SOME(x1), SOME(x2)) => valueEq(x1, x2)
    (_, _) => a1 === a2
  end
  b
end

""" a1 > a2? """
function valueCompare(a1::A, a2::A) where {A}
  local c1 = valueConstructor(a1)
  local c2 = valueConstructor(a2)
  c1 < c2 ? -1 : c1 > c2 ? 1 : 0
end

@inline function valueHashMod(value::A, m::Int) where {A}
  mod(Int(myhash(string(value))), m)
end

""" This is a very fast comparison of two values which only checks if the pointers are equal. """
@inline function referenceEq(a1::A1, a2::A2)::Bool where {A1,A2}
  a1 === a2
end

""" Returns the pointer address of a reference as a hexadecimal string that can
be used for debugging. """
function referencePointerString(ref::A)::String where {A}
  local str::String
  @assert false "not implemented"
  str
end

""" Use the diff to compare two time samples to each other. Not very accurate. """
function clock()::Float64
  local t::Float64
  @assert false "not implemented"
  t
end

""" Returns true if the input is NONE() """
@inline function isNone(opt::Option{A})::Bool where {A}
  opt === nothing
end

""" Returns true if the input is SOME() """
@inline function isSome(opt::Option{A})::Bool where {A}
  isa(opt, SOME)
end

function listStringCharString(strs::List{String})::String
  local str::String
  @assert false "not implemented"
  str
end

function stringCharListString(strs::List{String})::String
  local str::String = ""
  for s in strs
    str = str + s
  end
  str
end

const genericFailure = MetaModelicaGeneralException("Runtime defined generic Meta Modelica failure")

@noinline function fail()
  throw(genericFailure)
end

function fail(msg::String)
  throw(MetaModelicaGeneralException(msg))
end

""" Sets the stack overflow signal to the given value and returns the old one """
@inline function setStackOverflowSignal(inSignal::Bool)::Bool
  inSignal
end

function referenceDebugString(functionSymbol::A)::String where {A}
  local name::String
  @assert false "not implemented"
  name
end

"""
TODO: I am far from sure that this will fly.. in Julia.
The code generated from the transpiler is correct however
"""
@inline function isPresent(ident::T)::Bool where {T}
  true
end

#= The Info attribute provides location information for elements and classes. =#
@Mutable_Uniontype SourceInfo begin
  @Record SOURCEINFO begin
    fileName::String #= File where the class is defined. =#
    isReadOnly::Bool #= True for libraries. =#
    lineNumberStart::Int
    columnNumberStart::Int
    lineNumberEnd::Int
    columnNumberEnd::Int
    lastModification::Float64 #= stat(2) mtime as Float64 for precision on 32-bit platforms. =#
  end
end

SOURCEINFO(fileName::String, isReadOnly::Bool, lineNumberStart::Int,
           columnNumberSTart::Int, lineNumberEnd::Int,
           columnNumberEnd::Int) =
  let
    #= No source info. =#
    SOURCEINFO(fileName, isReadOnly, lineNumberStart, columnNumberSTart, lineNumberEnd,
               columnNumberEnd, 0.0)
  end

const DEFAULT_INFO = SOURCEINFO("", true, 1, 2, 3, 4, 0.0)

"""
Returns the default source info.
"""
@inline function sourceInfo()::SOURCEINFO
  DEFAULT_INFO
end

Base.:+(x::String, y::String) =
  let
    x * y
  end

""" Imports and prints if the import is successful. """
macro importDBG(moduleName)
  quote
    import $moduleName
    x = string(@__MODULE__)
    y = string($(esc(moduleName)))
    println("Importing " * y * " in " * x)
  end
end

const NOT_IMPLEMENTED_MSG::String = "__NOT_IMPLEMENTED__"

@inline function getInstanceName()::String
  NOT_IMPLEMENTED_MSG
end

@inline function StringFunction(i::Int64)::String
  intString(i)
end

@inline function StringFunction(r::Float64)::String
  realString(r)
end

function Base.String(arg)::String
  return string(arg)
end
